# SEED DATA FOR LOUDBOT 

module.exports = [
  "YA EMPEZAMOS DE VUELTA",
  "HABLE MÁS FUERTE QUE TENGO UNA TOALLA",
  "EN MI ÉPOCA ESTAS COSAS NO PASABAN",
  "ME PARECE BIEN",
  "NO HAY NECESIDAD",
  "POR ESTO MISMO NO PODEMOS TENER COSAS BUENAS",
  "A LA GRANDE LE PUSE CUCA",
  "(╯°□°）╯︵ ┻━┻",
  "UNA VEZ MÁS Y TE JURO",
  "NO ME DURÁS LO QUE UN SUGUS",
  "ಠ_ಠ",
  "Y?",
  "EXACTO"
]
